var annotated_dup =
[
    [ "apop_arms_settings", "structapop__arms__settings.html", "structapop__arms__settings" ],
    [ "apop_cdf_settings", "structapop__cdf__settings.html", "structapop__cdf__settings" ],
    [ "apop_composition_settings", "structapop__composition__settings.html", "structapop__composition__settings" ],
    [ "apop_coordinate_transform_settings", "structapop__coordinate__transform__settings.html", "structapop__coordinate__transform__settings" ],
    [ "apop_cross_settings", "structapop__cross__settings.html", "structapop__cross__settings" ],
    [ "apop_data", "structapop__data.html", "structapop__data" ],
    [ "apop_dconstrain_settings", "structapop__dconstrain__settings.html", "structapop__dconstrain__settings" ],
    [ "apop_kernel_density_settings", "structapop__kernel__density__settings.html", "structapop__kernel__density__settings" ],
    [ "apop_lm_settings", "structapop__lm__settings.html", "structapop__lm__settings" ],
    [ "apop_loess_settings", "structapop__loess__settings.html", "structapop__loess__settings" ],
    [ "apop_mcmc_proposal_s", "structapop__mcmc__proposal__s.html", "structapop__mcmc__proposal__s" ],
    [ "apop_mcmc_settings", "structapop__mcmc__settings.html", "structapop__mcmc__settings" ],
    [ "apop_mixture_settings", "structapop__mixture__settings.html", "structapop__mixture__settings" ],
    [ "apop_mle_settings", "structapop__mle__settings.html", "structapop__mle__settings" ],
    [ "apop_model", "structapop__model.html", "structapop__model" ],
    [ "apop_name", "structapop__name.html", "structapop__name" ],
    [ "apop_opts_type", "structapop__opts__type.html", "structapop__opts__type" ],
    [ "apop_parts_wanted_settings", "structapop__parts__wanted__settings.html", "structapop__parts__wanted__settings" ],
    [ "apop_pm_settings", "structapop__pm__settings.html", "structapop__pm__settings" ],
    [ "apop_pmf_settings", "structapop__pmf__settings.html", "structapop__pmf__settings" ],
    [ "apop_settings_type", "structapop__settings__type.html", "structapop__settings__type" ],
    [ "coeff_struct", "structcoeff__struct.html", "structcoeff__struct" ]
];