#!/bin/bash

junkdir=dists
pkg=apophenia
version=0.23
date=`date +%d_%b_%y`

#See README for notes.

#This script copies everything into a junk directory, that GNU's 
#prep materials will produce a thousand temp files in, concluding 
#with a file named apophenia-N.NN.tar.gz. Once that it is ready
#for distribution, the tar.gz arcive is copied to the main directory
#and this junk directory is erased. 
#If the appropriate tools are available, it also produces Debian pkgs.
#Finally, the script unzips the archive and compiles from the archive.

rm -rf $junkdir
mkdir $junkdir
mkdir $junkdir/$pkg-$version
shopt -s extglob  #makes the next line work
cp -rf !($junkdir) $junkdir/$pkg-$version
cd $junkdir/$pkg-$version
cp install/* .
mv Readme.user README
cp ChangeLog NEWS
sed -i "s/X\.XX/$version/" README apop_db.c configure.ac
sed -i -f prep_variadics.sed *c *h model/*c
	#add a directory with links to all headers:
	mkdir apophenia
	cd apophenia
		#cp ../*.h ./        #linking won't work for Windows
		#ln -s ../*.h ./
		cd ..
	#let the GNU prep everything and produce a distribution pkg.
    dot -Tpng < doxy/structs.dot | pngtopnm | pnmscale .5 | pnmtopng > doxy/structs.png
    echo "Ben Klemens (fluffmail@f-m.fm)" > AUTHORS
	libtoolize
    	aclocal
	autoconf 
	autoheader
	automake -a
	./configure
#	./configure --enable-python
#    yes | dh_make -l -n -c GPL  
#    cp ../../debian_control debian/control
#    cp ../../debian_copyright debian/copyright
#    debuild -us -uc 
#    rm ../$pkg-$version.tar.gz
	make dist
    mv apophenia-$version.tar.gz ../apophenia-$version-$date.tgz 
    make
    exit

#rm -rf $junkdir
echo "***********tgz done; now prepping Debian package*********************"
#Prerequisites: You will need the debian build tools; try:
# apt-get install dpkg-dev debhelper devscripts fakeroot linda dh-make 
#tar xz < apophenia-$version-#date.tar.gz


    #Uncomment the following to install from source
#cd $pkg-$version
#	sudo make install
#cd ..
    #Uncomment the following to install from debian pkg
	#sudo apt-get install apophenia-$version.deb
#mkdir dists
#mv apophenia-*.deb dists
#mv apophenia-*.gz dists
#mv apophenia_* dists


echo "***********Done with packing; now compiling***********"
cd $pkg-$version
./configure; make
