#! /usr/bin/ruby
#= Ruby Net::GitHub::Upload
# == INSTALL
# 
#  gem source -a http://gemcutter.org
#  sudo gem install net-github-upload
# == DEPENDENCY
# 
# * nokogiri
# * json
# * faster_xml_simple
# * httpclient
# 
# * http://github.com/Constellation/ruby-net-github-upload
# * http://gemcutter.org/gems/net-github-upload
# 
# == DESCRIPTION
# 
# Ruby Net::GitHub::Upload is upload user agent for GitHub Downloads
# respect to http://github.com/typester/net-github-upload-perl
# 

class String
  def force_encoding(enc)
    self
  end
end

  # require
  require 'rubygems'
  require 'net/github-upload'
  
  # setup
  login = `git config github.user`.chomp  # your login for github
  token = `git config github.token`.chomp # your token for github
  repos = 'Apophenia'               # your repos name (like 'taberareloo')
  gh = Net::GitHub::Upload.new(
    :login => login,
    :token => token
  )
  
  # file upload
#  direct_link = gh.upload(
#    :repos => repos,
#    :file  => 'test/test',
#    :description => "test file"
#  )
  # direct link is link to Amazon S3.
  # Because GitHub refrection for file changing is async,
  # if you get changed file synchronously, you use this "direct_link"
  
  # replace file or data
  # thx id:rngtng !

  direct_link = gh.upload(
    :repos => repos,
    :file  => 'apophenia-VERSION-DATE.tgz',
    :description => "The Apophenia source code: ./configure; make; sudo make install"
  )
  direct_link = gh.replace(
    :repos => repos,
    :file  => 'apophenia-VERSION-2_i386.deb',
    :description => "The Apophenia library as a Debian package (Experimental---please report install glitches)"
  )

  direct_link = gh.replace(
    :repos => repos,
    :file  => 'apophenia-VERSION-1.i386.rpm',
    :description => "The Apophenia library as an RPM package (Experimental---please report install glitches)"
  )

#  direct_link = gh.replace(
#    :repos => repos,
#    :file  => 'test/test',
#    :description => "test file"
#  )
